FROM node:22-bookworm-slim

# Install OpenSSL (Required by Prisma)
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

# 1. Install dependencies first (for caching)
COPY package*.json ./
RUN npm install

# 2. Copy the rest of the code (including prisma folder)
COPY . .

# 3. Generate the client using the stable v6 engine
RUN npx prisma generate

EXPOSE 8000

CMD ["npm", "run", "start"]
